# site settings
title: Forty
subtitle: by HTML5 UP
email: alicia.savelli@utoronto.ca
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/website"
url: "https://aliciasavelli.github.io"
author:
street_address: Canadian Institute for Theoretical Astrophysics, University of Toronto
city: Toronto
state: ON
zip_code: 
country: Canada
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/aliciasavelli
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/aliciamariesavelli/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
